version: 2

jobs:
  build:
    working_directory: /root/scala-xoroshiro128
    docker:
      - image: ubuntu:16.04
    steps:
      - run: >
          apt-get update
          && DEBIAN_FRONTEND=noninteractive apt-get install --yes
          curl git openjdk-8-jre-headless nodejs
          clang libgc-dev libunwind-dev
          && rm -rf /var/lib/apt/lists/*
          && ln -s /usr/bin/nodejs /usr/bin/node
      - run: mkdir -p ~/bin
      - run: curl -s https://raw.githubusercontent.com/paulp/sbt-extras/master/sbt > /usr/local/bin/sbt && chmod 0755 /usr/local/bin/sbt
      - checkout
      - restore_cache:
          key: dependency-cache-<< checksum "build.sbt" >>
          paths:
            - "~/.ivy2"
            - "~/.m2"
            - "~/.sbt"
            - "~/.lib"
      - run: sbt update
      - run: sbt benchmarkJVM/test:compile
      - run: sbt benchmarkJS/test:compile
      - run: sbt benchmarkNative/compile
      - save_cache:
          key: dependency-cache-<< checksum "build.sbt" >>
          paths:
            - "~/.ivy2"
            - "~/.m2"
            - "~/.sbt"
            - "~/.lib"
      - run: sbt scalastyle
      - run: sbt xoroshiro128JVM/test:test
      - run: sbt xoroshiro128JS/test:test
      - run: sbt benchmarkJVM/run
      - run: sbt benchmarkJS/run
      - run: sbt benchmarkNative/run
